apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subscriber"
        dapr.io/app-port: "6000"
      labels:
        app: subscriber
    spec:
      containers:
        - name: subscriber
          image: tommygood/dapr-subscriber:latest
          ports:
            - containerPort: 6000
