apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron # this is the name of the binding
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 10s" # valid cron schedule
  - name: direction
    value: "input"
