apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: app-access-policy
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
  metrics:
    enabled: true
    recordErrorCodes: true
  accessControl:
    defaultAction: deny
    trustDomain: "public"
    policies:
    - appId: service-invocation-frontend
      defaultAction: deny
      trustDomain: 'public'
      namespace: "default"
      operations:
      - name: /orders
        httpVerb: ['*']
        action: allow
