apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "publisher"
        dapr.io/app-port: "6000"
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher
          image: tommygood/dapr-publisher:latest
          command: ["node", "publisher.js"]
